# Generated by Django 4.2.3 on 2023-07-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Github link',
            field=models.URLField(default='github.com'),
        ),
    ]
