# Generated by Django 4.2.3 on 2023-07-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects_github_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Github link',
            new_name='github_link',
        ),
    ]
